using System.Collections.ObjectModel;
using ALLCOM_Test.ViewModels;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Input;
using Microsoft.UI.Xaml.Media;
using Microsoft.VisualBasic;
using Windows.Foundation.Metadata;
using ICommand = System.Windows.Input.ICommand;
using System;
using System.Runtime.InteropServices;
using CommunityToolkit.WinUI.UI;
using Microsoft.Graphics.Canvas;

namespace ALLCOM_Test.Views;
//public class DateSource
//{
//    DateSource()
//    {
//        Date = "0";
//        DateTime = new DateTime();
//        DataName = "name";
//    }
//    public required string Date
//    {
//        get; set;
//    }
//    public DateTime DateTime
//    {
//        get; set;
//    }
//    public required string DataName
//    {
//        get; set;
//    }
//}
public class DataListDatas
{
    public string DataName
    {
        get; set;
    }
    public string ID
    {
        get; set;
    }
    public double Data
    {
        get; set;
    }
    public ICommand Command
    {
        get; set;
    }


    public string Name => DataName;















    public DataListDatas(string dataName, double data, string id)
    {
        DataName = dataName;
        ID = id;
        Data = data;
        var deleteCommand = new StandardUICommand(StandardUICommandKind.Stop);
        // deleteCommand.ExecuteRequested += DeleteCommand_ExecuteRequested;
        Command = deleteCommand;
    }






    //private void DeleteCommand_ExecuteRequested(XamlUICommand sender, ExecuteRequestedEventArgs args)
    //{
    //    if (args.Parameter != null)
    //    {
    //        foreach (var i in dateSource)
    //        {
    //            if (i.Text == (args.Parameter as string))
    //            {
    //                collection.Remove(i);
    //                return;
    //            }
    //        }
    //    }
    //    if (ListViewRight.SelectedIndex != -1)
    //    {
    //        collection.RemoveAt(ListViewRight.SelectedIndex);
    //    }
    //}

    //private void ControlExample_Loaded(object sender, RoutedEventArgs e)
    //{
    //    if (ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 7))
    //    {
    //        var deleteCommand = new StandardUICommand(StandardUICommandKind.Delete);
    //        deleteCommand.ExecuteRequested += DeleteCommand_ExecuteRequested;

    //        Command = deleteCommand;


    //    }
    //    else
    //    {
    //        var deleteCommand = new StandardUICommand(StandardUICommandKind.Delete);
    //        deleteCommand.ExecuteRequested += DeleteCommand_ExecuteRequested;

    //        Command = deleteCommand;

    //    }
    //}



















}

// The ItemsSource for the ListView is generated by a method of the Contact class called
// GetContactsAsync().This method pulls data from an internal data source and creates
// Contact objects from that data. Those Contact objects are placed in a collection
// which is returned from the GetContactsAsync() function.

//BaseExample.ItemsSource = await Contact.GetContactsAsync();
public sealed partial class MainPage : Page
{
    public ObservableCollection<DataListDatas> dateSource = new(); //数据颜色

    public MainViewModel ViewModel
    {
        get;
    }

    public MainPage()
    {
        ViewModel = App.GetService<MainViewModel>();
        dateSource.Add(new DataListDatas("data0", 0, "0"));
        dateSource.Add(new DataListDatas("data1", 0, "1"));
        dateSource.Add(new DataListDatas("data2", 0, "2"));


        InitializeComponent();
    }
    private void TabView_Loaded(object sender, RoutedEventArgs e)
    {
        for (int i = 0; i < 1; i++)
        {
            if (sender != null)
            {
                (sender as TabView).TabItems.Add(CreateNewTab(i));

            }
        }

    }

    private void TabView_AddButtonClick(TabView sender, object args)
    {
        sender.TabItems.Add(CreateNewTab(sender.TabItems.Count));
    }

    private void TabView_TabCloseRequested(TabView sender, TabViewTabCloseRequestedEventArgs args)
    {
        sender.TabItems.Remove(args.Tab);
    }

    private TabViewItem CreateNewTab(int index)
    {
        TabViewItem newItem = new TabViewItem();

        newItem.Header = $"Document {index}";
        newItem.IconSource = new Microsoft.UI.Xaml.Controls.SymbolIconSource() { Symbol = Symbol.Document };

        // The content of the tab is often a frame that contains a page, though it could be any UIElement.
        Frame frame = new Frame();

        switch (index % 3)
        {
            case 0:
                frame.Navigate(typeof(MainCanvasPage));
                break;
            case 1:
                frame.Navigate(typeof(MainCanvasPage));
                break;
            case 2:
                frame.Navigate(typeof(MainCanvasPage));
                break;
        }

        newItem.Content = frame;

        return newItem;
    }

    private void HoverButton_Click(object sender, RoutedEventArgs e)
    {
        AppBarButton? button = sender as AppBarButton;
        if (button != null)
        {
            //button.Label = "FontIcon";
            var fontIcon = new FontIcon();
            fontIcon.FontFamily = new FontFamily("Segoe UI Emoji");
            fontIcon.Glyph = "\uE769";
            // button.Icon = fontIcon;

        }

    }
    // C# code-behind

    // The data template is defined to display a Contact object (class definition shown below), and the text
    // displayed is bound to the Contact object's Name attribute.


}
